#pragma once

#include "../FRIDefinitions.h"

#define DEFINE_PROXY_ENUM(efri, dx) case efri: return dx

FORCEINLINE D3D12_TEXTURE_ADDRESS_MODE D3D12GetTextureAddressMode(EFRITextureAddress address)
{
	switch (address)
	{
	case EFRITextureAddress::Repeat: return D3D12_TEXTURE_ADDRESS_MODE_WRAP;
	case EFRITextureAddress::MirroredRepeat: return D3D12_TEXTURE_ADDRESS_MODE_MIRROR;
	case EFRITextureAddress::ClampBorder: return D3D12_TEXTURE_ADDRESS_MODE_BORDER;
	case EFRITextureAddress::ClampEdge: return D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
	}
	return D3D12_TEXTURE_ADDRESS_MODE_WRAP;
}

FORCEINLINE D3D12_FILTER D3D12GetTextureFilter(EFRITextureFilter filter)
{
	switch (filter)
	{
	case EFRITextureFilter::Point: return D3D12_FILTER_MIN_MAG_MIP_POINT;
	case EFRITextureFilter::Bilinear: return D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT;
	case EFRITextureFilter::Trilinear: return D3D12_FILTER_MIN_MAG_MIP_LINEAR;
	case EFRITextureFilter::Anisotropic4: return D3D12_FILTER_ANISOTROPIC;
	case EFRITextureFilter::Anisotropic8: return D3D12_FILTER_ANISOTROPIC;
	}
	return D3D12_FILTER_MIN_MAG_MIP_POINT;
}

FORCEINLINE D3D12_BLEND D3D12GetBlend(EFRIBlend blend)
{
	switch (blend)
	{
	case EFRIBlend::Dst: return D3D12_BLEND_DEST_ALPHA;
	case EFRIBlend::Src: return D3D12_BLEND_SRC_ALPHA;
	case EFRIBlend::One: return D3D12_BLEND_ONE;
	case EFRIBlend::Zero: return D3D12_BLEND_ZERO;
	case EFRIBlend::OneMinusSrc: return D3D12_BLEND_INV_SRC_ALPHA;
	case EFRIBlend::OneMinusDst: return D3D12_BLEND_INV_DEST_ALPHA;
	}
	return D3D12_BLEND_ONE;
}

FORCEINLINE DXGI_FORMAT EDX12FormatProxyEnum(EFRITextureFormat format)
{
	switch (format)
	{
		// FLOAT
		DEFINE_PROXY_ENUM(EFRITextureFormat::R32F, DXGI_FORMAT_R32_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG32F, DXGI_FORMAT_R32G32_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGB32F, DXGI_FORMAT_R32G32B32_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA32F, DXGI_FORMAT_R32G32B32A32_FLOAT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R16F, DXGI_FORMAT_R16_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG16F, DXGI_FORMAT_R16G16_FLOAT);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB16F, DXGI_FORMAT_R16G16B16_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA16F, DXGI_FORMAT_R16G16B16A16_FLOAT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R16UNORM, DXGI_FORMAT_R16_UNORM);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG16UNORM, DXGI_FORMAT_R16G16_UNORM);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB16F, DXGI_FORMAT_R16G16B16_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA16UNORM, DXGI_FORMAT_R16G16B16A16_UNORM);

		//UNISNGED INT

		DEFINE_PROXY_ENUM(EFRITextureFormat::R32UI, DXGI_FORMAT_R32_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG32UI, DXGI_FORMAT_R32G32_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGB32UI, DXGI_FORMAT_R32G32B32_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA32UI, DXGI_FORMAT_R32G32B32A32_UINT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R16UI, DXGI_FORMAT_R16_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG16UI, DXGI_FORMAT_R16G16_UINT);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB16UI, DXGI_FORMAT_R16G16B16_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA16UI, DXGI_FORMAT_R16G16B16A16_UINT);


		// BYTE

		DEFINE_PROXY_ENUM(EFRITextureFormat::R8UI, DXGI_FORMAT_R8_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG8UI, DXGI_FORMAT_R8G8_UINT);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB8UI, DXGI_FORMAT_R8G8B8_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA8UI, DXGI_FORMAT_R8G8B8A8_UINT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R8UNORM, DXGI_FORMAT_R8_UNORM);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG8UNORM, DXGI_FORMAT_R8G8_UNORM);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB8UI, DXGI_FORMAT_R8G8B8_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA8UNORM, DXGI_FORMAT_R8G8B8A8_UNORM);

		DEFINE_PROXY_ENUM(EFRITextureFormat::DEPTH32, DXGI_FORMAT_D32_FLOAT);

	default: return DXGI_FORMAT_UNKNOWN;
	}
	return DXGI_FORMAT_UNKNOWN;
}