#pragma once

#include "../dll/nchfx.h"




EXPORT_STRUCT Color : fVector4
{
public:
	Color(BYTE r, BYTE g, BYTE b);
	Color(BYTE r, BYTE g, BYTE b, BYTE a);
	Color(_UNS_ FL_INT32 hex);

	static Color aliceblue;
	static Color antiquewhite;
	static Color aqua;
	static Color aquamarine;
	static Color azure;
	static Color beige;
	static Color bisque;
	static Color black;
	static Color blanchedalmond;
	static Color blue;
	static Color blueviolet;
	static Color brown;
	static Color burlywood;
	static Color cadetblue;
	static Color chartreuse;
	static Color chocolate;
	static Color coral;
	static Color cornflowerblue;
	static Color cornsilk;
	static Color crimson;
	static Color cyan;
	static Color darkblue;
	static Color darkcyan;
	static Color darkgoldenrod;
	static Color darkgray;
	static Color darkgreen;
	static Color darkkhaki;
	static Color darkmagenta;
	static Color darkolivegreen;
	static Color darkorange;
	static Color darkorchid;
	static Color darkred;
	static Color darksalmon;
	static Color darkseagreen;
	static Color darkslateblue;
	static Color darkslategray;
	static Color darkturquoise;
	static Color darkviolet;
	static Color deeppink;
	static Color deepskyblue;
	static Color dimgray;
	static Color dodgerblue;
	static Color firebrick;
	static Color floralwhite;
	static Color forestgreen;
	static Color fuchsia;
	static Color gainsboro;
	static Color ghostwhite;
	static Color gold;
	static Color goldenrod;
	static Color gray;
	static Color green;
	static Color greenyellow;
	static Color honeydew;
	static Color hotpink;
	static Color indianred;
	static Color indigo;
	static Color ivory;
	static Color khaki;
	static Color lavender;
	static Color lavenderblush;
	static Color lawngreen;
	static Color lemonchiffon;
	static Color lightblue;
	static Color lightcoral;
	static Color lightcyan;
	static Color lightgoldenrodyellow;
	static Color lightgray;
	static Color lightgreen;
	static Color lightpink;
	static Color lightsalmon;
	static Color lightseagreen;
	static Color lightskyblue;
	static Color lightslategray;
	static Color lightsteelblue;
	static Color lightyellow;
	static Color lime;
	static Color limegreen;
	static Color linen;
	static Color magenta;
	static Color maroon;
	static Color mediumaquamarine;
	static Color mediumblue;
	static Color mediumorchid;
	static Color mediumpurple;
	static Color mediumseagreen;
	static Color mediumslateblue;
	static Color mediumspringgreen;
	static Color mediumturquoise;
	static Color mediumvioletred;
	static Color midnightblue;
	static Color mintcream;
	static Color mistyrose;
	static Color moccasin;
	static Color navajowhite;
	static Color navy;
	static Color oldlace;
	static Color olive;
	static Color olivedrab;
	static Color orange;
	static Color orangered;
	static Color orchid;
	static Color palegoldenrod;
	static Color palegreen;
	static Color paleturquoise;
	static Color palevioletred;
	static Color papayawhip;
	static Color peachpuff;
	static Color peru;
	static Color pink;
	static Color plum;
	static Color powderblue;
	static Color purple;
	static Color red;
	static Color rosybrown;
	static Color royalblue;
	static Color saddlebrown;
	static Color salmon;
	static Color sandybrown;
	static Color seagreen;
	static Color seashell;
	static Color sienna;
	static Color silver;
	static Color skyblue;
	static Color slateblue;
	static Color slategray;
	static Color snow;
	static Color springgreen;
	static Color steelblue;
	static Color tan;
	static Color teal;
	static Color thistle;
	static Color tomato;
	static Color turquoise;
	static Color violet;
	static Color wheat;
	static Color white;
	static Color whitesmoke;
	static Color yellow;
	static Color yellowgreen;
};

