#pragma once


#include "../dll/nchfx.h"


EXPORT_ENUM TextureFiltering
{
	NONE,
	BILINEAR,
	TRILINEAR,
	ANISOTROPIC_8,
	ANISOTROPIC_16
};

EXPORT_ENUM TextureWrapping
{
	REPEAT = GL_REPEAT,
	CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
	CLAMP_TO_BORDER = GL_CLAMP_TO_BORDER,
	MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
	MIRRORED_CLAMP_TO_EDGE = GL_MIRROR_CLAMP_TO_EDGE
};