#pragma once

#include "D3D11.h"
#include "../FRIDefinitions.h"


#define DEFINE_PROXY_ENUM(efri, dx) case efri: return dx



FORCEINLINE DXGI_FORMAT EDX11FormatProxyEnum(EFRITextureFormat format)
{
	switch (format)
	{
		// FLOAT
		DEFINE_PROXY_ENUM(EFRITextureFormat::R32F, DXGI_FORMAT_R32_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG32F, DXGI_FORMAT_R32G32_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGB32F, DXGI_FORMAT_R32G32B32_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA32F, DXGI_FORMAT_R32G32B32A32_FLOAT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R16F, DXGI_FORMAT_R16_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG16F, DXGI_FORMAT_R16G16_FLOAT);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB16F, DXGI_FORMAT_R16G16B16_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA16F, DXGI_FORMAT_R16G16B16A16_FLOAT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R16UNORM, DXGI_FORMAT_R16_UNORM);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG16UNORM, DXGI_FORMAT_R16G16_UNORM);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB16F, DXGI_FORMAT_R16G16B16_FLOAT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA16UNORM, DXGI_FORMAT_R16G16B16A16_UNORM);

		//UNISNGED INT

		DEFINE_PROXY_ENUM(EFRITextureFormat::R32UI, DXGI_FORMAT_R32_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG32UI, DXGI_FORMAT_R32G32_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGB32UI, DXGI_FORMAT_R32G32B32_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA32UI, DXGI_FORMAT_R32G32B32A32_UINT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R16UI, DXGI_FORMAT_R16_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG16UI, DXGI_FORMAT_R16G16_UINT);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB16UI, DXGI_FORMAT_R16G16B16_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA16UI, DXGI_FORMAT_R16G16B16A16_UINT);


		// BYTE

		DEFINE_PROXY_ENUM(EFRITextureFormat::R8UI, DXGI_FORMAT_R8_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG8UI, DXGI_FORMAT_R8G8_UINT);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB8UI, DXGI_FORMAT_R8G8B8_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA8UI, DXGI_FORMAT_R8G8B8A8_UINT);

		DEFINE_PROXY_ENUM(EFRITextureFormat::R8UNORM, DXGI_FORMAT_R8_UNORM);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RG8UNORM, DXGI_FORMAT_R8G8_UNORM);
		//DEFINE_PROXY_ENUM(EFRITextureFormat::RGB8UI, DXGI_FORMAT_R8G8B8_UINT);
		DEFINE_PROXY_ENUM(EFRITextureFormat::RGBA8UNORM, DXGI_FORMAT_R8G8B8A8_UNORM);

		DEFINE_PROXY_ENUM(EFRITextureFormat::DEPTH32, DXGI_FORMAT_D32_FLOAT);

		default: return DXGI_FORMAT_UNKNOWN;
	}
	return DXGI_FORMAT_UNKNOWN;
}
